"""
xmlio.py
========

Import / export of the borough's management plan as an *office spreadsheet*.

Supports BOTH ODS (OpenDocument Spreadsheet, default) and XML (SpreadsheetML 2003).
The user can choose the format via file dialog. ODS is the default format.

The on-disk format for XML is SpreadsheetML 2003 -- the classic
``<?mso-application progid="Excel.Sheet"?>`` XML that Excel and LibreOffice
both open natively.

For ODS, we use pyexcel-ods (which wraps odfpy) for a clean, dependency-light
approach that produces properly formatted .ods files.

Worksheets:
    Summary             borough header + read-me
    Collection Rounds   per-round day + weekly/fortnightly frequency   (editable)
    Waste Streams       which streams are collected + how often         (editable)
    Finance             tax/rate levers + a profit & loss snapshot      (rates editable)
    Routes              routing levers (service threshold)              (editable)
    Staff               crew headcount + a target to hire toward        (target editable)
    Fleet               current vehicles                                (export only)
    Procurement Orders  vehicles on order                               (export only)

Import is deliberately non-destructive about money: it applies the levers you
can safely round-trip and only ever *hires* crew within budget, so loading a
plan can never silently bankrupt the council. Buy and scrap vehicles from the
Fleet tab.
"""

import os
import datetime
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape, quoteattr
from collections import OrderedDict

from procurement import VEHICLE_CATALOGUE, get_vehicle

DAY_FULL = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
            "Saturday", "Sunday"]
DAY_ABBR = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

PRODUCT = "KerbsidePlanner Council Edition"


# ---------------------------------------------------------------------------
#  Shared helpers (used by both ODS and XML builders + the import path)
# ---------------------------------------------------------------------------

def _truck_round_label(game, truck):
    """Human-readable name of the round a lorry is pinned to ('Auto' = none)."""
    pref = truck.get("preferred_area", -1)
    if pref is None or pref < 0:
        return "Auto"
    area = game.city.get_area(pref)
    return area.name if area else "Auto"


def _round_id_from_cell(game, value):
    """Resolve a Fleet-sheet 'Round' cell to an area id. Accepts an area name,
    a numeric id, or 'Auto'/'-'/'' (-> -1 for automatic)."""
    if value is None:
        return -1
    s = str(value).strip()
    if s == "" or s.lower() in ("auto", "-", "none", "any"):
        return -1
    # Numeric id?
    try:
        return int(float(s))
    except (ValueError, TypeError):
        pass
    low = s.lower()
    for area in game.city.areas:
        if area.name.strip().lower() == low:
            return area.id
    return -1


def _is_lease(value):
    return str(value or "").strip().lower().startswith("lease")


def _last_import_lines(game):
    """Lines describing the most recent import (for the Summary sheet). Empty
    if nothing has been imported yet this session."""
    report = getattr(game, "last_import_report", None)
    if not report:
        return []
    stamp = getattr(game, "last_import_stamp", "")
    out = ["", f"Last import ({stamp})" if stamp else "Last import"]
    out.extend(f"  {line}" for line in report)
    return out

# Finance lever labels -- export and import must agree on these exact strings.
LV_COUNCIL_TAX = "Council tax (GBP / resident / day)"
LV_BUSINESS = "Business rates (GBP / premises / day)"
LV_WAGE = "Crew wage (GBP / hour)"
LV_THRESHOLD = "Service threshold (% full)"
LV_TARGET_CREW = "Target crew headcount"

# Config sheet lever labels.
LV_DAY_LENGTH = "Day length (seconds)"
LV_EVENT_CHANCE = "Random event chance (0-1 per day)"
LV_WIN_TARGET = "Win: consecutive clean days needed"


# ===========================================================================
#  ODS Support (via pyexcel-ods)
# ===========================================================================

def _has_pyexcel_ods():
    try:
        import pyexcel_ods
        return True
    except ImportError:
        return False


def _build_ods_data(game):
    """Build an OrderedDict of sheet data for pyexcel-ods."""
    eco = game.economy
    city = game.city
    fleet = game.fleet
    waste = game.waste
    today = eco.get_day_of_week()
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    data = OrderedDict()

    # -- Summary ------------------------------------------------------------
    led = eco.ledger_snapshot()
    summary = [
        ["Borough Waste Services", "Management Plan"],
        [f"Generated by {PRODUCT}  *  {stamp}", ""],
        ["", ""],
        ["Borough at a glance", ""],
        ["Simulation day", eco.day],
        ["Weekday", DAY_FULL[today]],
        ["Week number", eco.week_index + 1],
        ["Population", city.population],
        ["Properties", city.property_count],
        ["Budget", int(eco.budget)],
        ["Public satisfaction", round(eco.satisfaction, 1)],
        ["Net yesterday", int(led["net"])],
        ["", ""],
        ["How to use this file", ""],
        ["Edit the highlighted tabs, save, then re-import from the Data tab.", ""],
        ["Editable: Collection Rounds, Waste Streams, Finance rates, Routes,", ""],
        ["Staff, Fleet (crew / round / scrap), Place Orders and Config.", ""],
        ["Read-only: Catalogue, Procurement Orders and the P&L figures.", ""],
    ]
    for line in _last_import_lines(game):
        summary.append([line, ""])
    data["Summary"] = summary

    # -- Collection Rounds --------------------------------------------------
    rounds = [
        ["Round", "Id", "Collection day", "Frequency", "Properties",
         "Population", "Avg fill %", "Status", "Route type"]
    ]
    for area in city.areas:
        st = city.area_stats(area.id, today)
        rounds.append([
            area.name,
            area.id,
            DAY_ABBR[area.collection_day],
            "Fortnightly" if area.frequency >= 2 else "Weekly",
            area.property_count,
            area.population,
            int(st["avg"]) if st else 0,
            st["status"] if st else "-",
            area.route_type,
        ])
    data["Collection Rounds"] = rounds

    # -- Waste Streams ------------------------------------------------------
    wr = waste.to_rows()
    streams = [
        ["Stream", "Id", "Collected", "Frequency", "Gate fee (GBP/unit)",
         "Credit (GBP/unit)", "Satisfaction", "Note"]
    ]
    for r in wr:
        streams.append([
            r["Stream"], r["Id"], r["Collected"], r["Frequency"],
            r["Gate fee (GBP/unit)"], r["Credit (GBP/unit)"],
            r["Satisfaction"], r["Note"],
        ])
    data["Waste Streams"] = streams

    # -- Finance ------------------------------------------------------------
    finance = [
        ["Item", "Type", "Value"]
    ]
    finance.append([LV_COUNCIL_TAX, "rate", round(eco.council_tax_rate, 2)])
    finance.append([LV_BUSINESS, "rate", round(eco.business_rates, 2)])
    finance.append([LV_WAGE, "rate", round(eco.hourly_wage_rate, 2)])
    finance.append(["", "", ""])
    finance.append(["Profit & loss (yesterday)", "", ""])
    for key, label in eco.LEDGER_LABELS:
        val = int(round(led.get(key, 0.0)))
        kind = "revenue" if key in eco.REVENUE_KEYS else "expense"
        finance.append([label, kind, val])
    finance.append(["NET", "net", int(round(led["net"]))])
    data["Finance"] = finance

    # -- Routes -------------------------------------------------------------
    routes = [
        ["Item", "Value"]
    ]
    routes.append([LV_THRESHOLD, int(fleet.service_threshold)])
    routes.append(["Bins due today", fleet.get_today_demand()])
    routes.append(["Estimated daily capacity (bins)", fleet.estimated_daily_capacity()])
    routes.append(["Active lorries", fleet.active_lorries()])
    routes.append(["Collections (lifetime)", fleet.collected_count])
    data["Routes"] = routes

    # -- Staff --------------------------------------------------------------
    lorries = max(1, len(fleet.trucks))
    staff = [
        ["Item", "Value"]
    ]
    staff.append(["Total crew", fleet.workers])
    staff.append(["Lorries", len(fleet.trucks)])
    staff.append(["Crew per lorry (avg)", round(fleet.workers / lorries, 2)])
    staff.append([LV_TARGET_CREW, fleet.workers])
    data["Staff"] = staff

    # -- Fleet (editable: Crew, Round, Scrap?) ------------------------------
    fleet_sheet = [
        ["Lorry", "Id", "Model", "Capacity", "Crew", "Crew cap",
         "Round", "Scrap?", "Tenure", "Status"]
    ]
    for t in fleet.trucks:
        fleet_sheet.append([
            f"L{t['id']}",
            t["id"],
            t.get("model_name", "Standard"),
            int(t["capacity"]),
            t["crew"],
            t.get("crew_cap", 3),
            _truck_round_label(game, t),
            "No",
            "Leased" if t.get("leased") else "Owned",
            t["state"],
        ])
    if not fleet.trucks:
        fleet_sheet.append(["(no vehicles)", "", "", "", "", "", "", "", "", ""])
    data["Fleet"] = fleet_sheet

    # -- Catalogue (read-only reference) ------------------------------------
    catalogue = [
        ["Model id", "Model", "Capacity", "Crew cap", "Speed x", "Price (GBP)",
         "Lease/week (GBP)", "Lease deposit (GBP)", "Running/day (GBP)",
         "Lead (days)", "Notes"]
    ]
    for v in VEHICLE_CATALOGUE:
        catalogue.append([
            v.id, v.name, v.capacity, v.crew_cap, v.speed_factor, v.price,
            v.lease_weekly, v.deposit(), v.running_cost, v.lead_time, v.blurb,
        ])
    data["Catalogue"] = catalogue

    # -- Place Orders (editable: set Quantity > 0 to order) -----------------
    place = [
        ["Model id", "Quantity", "Tenure (Buy/Lease)", "Up-front each (GBP)",
         "Lead (days)", "Note"]
    ]
    for v in VEHICLE_CATALOGUE:
        place.append([
            v.id, 0, "Buy", v.price, v.lead_time,
            f"{v.name} -- lease deposit GBP{v.deposit()}",
        ])
    data["Place Orders"] = place

    # -- Procurement Orders (read-only -- vehicles already on order) --------
    orders = [
        ["Model", "Ordered (day)", "Arrives (day)", "Days left", "Tenure"]
    ]
    for o in fleet.orders:
        orders.append([
            o.vehicle.name,
            o.order_day,
            o.arrival_day,
            o.days_remaining(eco.day),
            "Leased" if o.leased else "Owned",
        ])
    if not fleet.orders:
        orders.append(["(nothing on order)", "", "", "", ""])
    data["Procurement Orders"] = orders

    # -- Config (editable difficulty / pacing levers) -----------------------
    config = [
        ["Item", "Value"],
        [LV_DAY_LENGTH, round(eco.day_duration, 1)],
        [LV_EVENT_CHANCE, round(eco.event_chance, 2)],
        [LV_WIN_TARGET, eco.win_streak_target],
    ]
    data["Config"] = config

    return data


def export_to_ods_path(game, path):
    """Export game state to an ODS file."""
    from pyexcel_ods import save_data
    data = _build_ods_data(game)
    save_data(path, data)
    return path


def import_from_ods_path(game, path):
    """Import game state from an ODS file."""
    from pyexcel_ods import get_data
    data = get_data(path)
    sheets = {}
    for sheet_name, rows in data.items():
        if not rows:
            continue
        headers = [str(h).strip() for h in rows[0]]
        rowdicts = []
        for cells in rows[1:]:
            d = {}
            for i, h in enumerate(headers):
                d[h] = cells[i] if i < len(cells) else ""
            rowdicts.append(d)
        sheets[sheet_name] = rowdicts
    return apply_workbook(game, sheets)


# ===========================================================================
#  XML Support (SpreadsheetML 2003)
# ===========================================================================

def _day_index(name):
    if name is None:
        return None
    n = str(name).strip().lower()[:3]
    for i, a in enumerate(DAY_ABBR):
        if a.lower() == n:
            return i
    return None


def _cell(value, style=None, formula=None):
    """One <Cell>. Numbers export as Number, everything else as String."""
    attrs = ""
    if style:
        attrs += f' ss:StyleID={quoteattr(style)}'
    if formula:
        attrs += f' ss:Formula={quoteattr(formula)}'
    if isinstance(value, bool):
        value = "Yes" if value else "No"
    if isinstance(value, (int, float)):
        return (f'<Cell{attrs}><Data ss:Type="Number">'
                f'{value}</Data></Cell>')
    text = escape("" if value is None else str(value))
    return f'<Cell{attrs}><Data ss:Type="String">{text}</Data></Cell>'


def _row(cells, height=None):
    attrs = f' ss:Height="{height}"' if height else ""
    return f"<Row{attrs}>{''.join(cells)}</Row>"


def _sheet(name, columns, rows, freeze_header=True):
    cols = "".join(f'<Column ss:Width="{w}"/>' for w in columns)
    body = "".join(rows)
    opts = (
        '<WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">'
        '<PageSetup><Layout x:Orientation="Landscape"/></PageSetup>'
        '<FitToPage/>'
    )
    if freeze_header:
        opts += ('<FreezePanes/><FrozenNoSplit/>'
                 '<SplitHorizontal>1</SplitHorizontal>'
                 '<TopRowBottomPane>1</TopRowBottomPane>'
                 '<ActivePane>2</ActivePane>')
    opts += '</WorksheetOptions>'
    return (f'<Worksheet ss:Name={quoteattr(name)}><Table>'
            f'{cols}{body}</Table>{opts}</Worksheet>')


_STYLES = """
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/><Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="11" ss:Color="#1F2430"/>
   <Interior/><NumberFormat/><Protection/>
  </Style>
  <Style ss:ID="title">
   <Font ss:FontName="Calibri Light" ss:Size="20" ss:Bold="1" ss:Color="#243B53"/>
  </Style>
  <Style ss:ID="subtitle">
   <Font ss:FontName="Calibri" ss:Size="11" ss:Italic="1" ss:Color="#62748A"/>
  </Style>
  <Style ss:ID="hdr">
   <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>
   <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/>
   <Interior ss:Color="#334E68" ss:Pattern="Solid"/>
   <Borders>
    <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#1F2933"/>
   </Borders>
  </Style>
  <Style ss:ID="hdrnum" ss:Parent="hdr">
   <Alignment ss:Horizontal="Right" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="label">
   <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#334E68"/>
  </Style>
  <Style ss:ID="money">
   <NumberFormat ss:Format="&quot;GBP&quot;\\ #,##0"/>
  </Style>
  <Style ss:ID="money2">
   <NumberFormat ss:Format="&quot;GBP&quot;\\ #,##0.00"/>
  </Style>
  <Style ss:ID="pct">
   <NumberFormat ss:Format="0&quot;%&quot;"/>
  </Style>
  <Style ss:ID="note">
   <Alignment ss:WrapText="1" ss:Vertical="Top"/>
   <Font ss:FontName="Calibri" ss:Size="10" ss:Italic="1" ss:Color="#62748A"/>
  </Style>
  <Style ss:ID="band">
   <Interior ss:Color="#F0F4F8" ss:Pattern="Solid"/>
  </Style>
 </Styles>
"""


def _header_row(titles, numeric_cols=()):
    cells = []
    for i, t in enumerate(titles):
        cells.append(_cell(t, "hdrnum" if i in numeric_cols else "hdr"))
    return _row(cells, height=20)


def build_workbook_xml(game):
    eco = game.economy
    city = game.city
    fleet = game.fleet
    waste = game.waste
    today = eco.get_day_of_week()
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    sheets = []

    # -- Summary ------------------------------------------------------------
    led = eco.ledger_snapshot()
    rows = [
        _row([_cell("Borough Waste Services", "title")], height=30),
        _row([_cell("Management Plan", "title")], height=28),
        _row([_cell(f"Generated by {PRODUCT}  *  {stamp}", "subtitle")]),
        _row([_cell("")]),
        _row([_cell("Borough at a glance", "label")]),
        _row([_cell("Simulation day"), _cell(eco.day)]),
        _row([_cell("Weekday"), _cell(DAY_FULL[today])]),
        _row([_cell("Week number"), _cell(eco.week_index + 1)]),
        _row([_cell("Population"), _cell(city.population)]),
        _row([_cell("Properties"), _cell(city.property_count)]),
        _row([_cell("Budget"), _cell(int(eco.budget), "money")]),
        _row([_cell("Public satisfaction"), _cell(round(eco.satisfaction, 1))]),
        _row([_cell("Net yesterday"), _cell(int(led["net"]), "money")]),
        _row([_cell("")]),
        _row([_cell("How to use this file", "label")]),
        _row([_cell("Edit the highlighted tabs in your spreadsheet app, save as "
                    "XML Spreadsheet 2003 (*.xml) or ODS,", "note")]),
        _row([_cell("then re-import from the borough's Data tab. Editable: "
                    "Collection Rounds, Waste Streams,", "note")]),
        _row([_cell("Finance rates, Routes, Staff, Fleet (crew / round / "
                    "scrap), Place Orders and Config.", "note")]),
        _row([_cell("Read-only: Catalogue, Procurement Orders and the P&L "
                    "figures.", "note")]),
    ]
    imp_lines = _last_import_lines(game)
    if imp_lines:
        rows.append(_row([_cell("")]))
        rows.append(_row([_cell(imp_lines[1], "label")]))
        for line in imp_lines[2:]:
            rows.append(_row([_cell(line, "note")]))
    sheets.append(_sheet("Summary", [150, 220], rows, freeze_header=False))

    # -- Collection Rounds --------------------------------------------------
    rows = [_header_row(
        ["Round", "Id", "Collection day", "Frequency", "Properties",
         "Population", "Avg fill %", "Status", "Route type"],
        numeric_cols=(1, 4, 5, 6))]
    for area in city.areas:
        st = city.area_stats(area.id, today)
        band = "band" if area.id % 2 else None
        rows.append(_row([
            _cell(area.name, band),
            _cell(area.id, band),
            _cell(DAY_ABBR[area.collection_day], band),
            _cell("Fortnightly" if area.frequency >= 2 else "Weekly", band),
            _cell(area.property_count, band),
            _cell(area.population, band),
            _cell(int(st["avg"]) if st else 0, band),
            _cell(st["status"] if st else "-", band),
            _cell(area.route_type, band),
        ]))
    sheets.append(_sheet("Collection Rounds",
                         [150, 50, 90, 90, 80, 80, 70, 100, 80], rows))

    # -- Waste Streams ------------------------------------------------------
    wr = waste.to_rows()
    rows = [_header_row(
        ["Stream", "Id", "Collected", "Frequency", "Gate fee (GBP/unit)",
         "Credit (GBP/unit)", "Satisfaction", "Note"], numeric_cols=(4, 5, 6))]
    for i, r in enumerate(wr):
        band = "band" if i % 2 else None
        rows.append(_row([
            _cell(r["Stream"], band),
            _cell(r["Id"], band),
            _cell(r["Collected"], band),
            _cell(r["Frequency"], band),
            _cell(r["Gate fee (GBP/unit)"], "money2"),
            _cell(r["Credit (GBP/unit)"], "money2"),
            _cell(r["Satisfaction"], band),
            _cell(r["Note"], "note"),
        ]))
    sheets.append(_sheet("Waste Streams", [150, 80, 80, 100, 110, 110, 90, 320], rows))

    # -- Finance ------------------------------------------------------------
    rows = [_header_row(["Item", "Type", "Value"], numeric_cols=(2,))]

    def fin(item, typ, value, style=None):
        return _row([_cell(item, "label" if typ == "rate" else None),
                     _cell(typ), _cell(value, style)])

    rows.append(fin(LV_COUNCIL_TAX, "rate", round(eco.council_tax_rate, 2), "money2"))
    rows.append(fin(LV_BUSINESS, "rate", round(eco.business_rates, 2), "money2"))
    rows.append(fin(LV_WAGE, "rate", round(eco.hourly_wage_rate, 2), "money2"))
    rows.append(_row([_cell("")]))
    rows.append(_row([_cell("Profit & loss (yesterday)", "label")]))

    # Track the spreadsheet row numbers of the P&L block so NET can be a live
    # formula (Type in column 2, Value in column 3). 1-based, +1 for header.
    ledger_start = len(rows) + 1
    for key, label in eco.LEDGER_LABELS:
        val = int(round(led.get(key, 0.0)))
        kind = "revenue" if key in eco.REVENUE_KEYS else "expense"
        rows.append(fin(label, kind, val, "money"))
    ledger_end = len(rows)

    net_formula = (
        f'=SUMIF(R{ledger_start}C2:R{ledger_end}C2,"revenue",'
        f'R{ledger_start}C3:R{ledger_end}C3)'
        f'-SUMIF(R{ledger_start}C2:R{ledger_end}C2,"expense",'
        f'R{ledger_start}C3:R{ledger_end}C3)'
    )
    rows.append(_row([
        _cell("NET", "label"),
        _cell("net"),
        _cell(int(round(led["net"])), "money", formula=net_formula),
    ]))
    sheets.append(_sheet("Finance", [260, 90, 110], rows))

    # -- Routes -------------------------------------------------------------
    rows = [_header_row(["Item", "Value"], numeric_cols=(1,))]
    rows.append(_row([_cell(LV_THRESHOLD, "label"),
                      _cell(int(fleet.service_threshold))]))
    rows.append(_row([_cell("Bins due today"), _cell(fleet.get_today_demand())]))
    rows.append(_row([_cell("Estimated daily capacity (bins)"),
                      _cell(fleet.estimated_daily_capacity())]))
    rows.append(_row([_cell("Active lorries"), _cell(fleet.active_lorries())]))
    rows.append(_row([_cell("Collections (lifetime)"), _cell(fleet.collected_count)]))
    sheets.append(_sheet("Routes", [260, 110], rows))

    # -- Staff --------------------------------------------------------------
    lorries = max(1, len(fleet.trucks))
    rows = [_header_row(["Item", "Value"], numeric_cols=(1,))]
    rows.append(_row([_cell("Total crew"), _cell(fleet.workers)]))
    rows.append(_row([_cell("Lorries"), _cell(len(fleet.trucks))]))
    rows.append(_row([_cell("Crew per lorry (avg)"),
                      _cell(round(fleet.workers / lorries, 2))]))
    rows.append(_row([_cell(LV_TARGET_CREW, "label"), _cell(fleet.workers)]))
    sheets.append(_sheet("Staff", [260, 110], rows))

    # -- Fleet (editable: Crew, Round, Scrap?) ------------------------------
    rows = [_header_row(
        ["Lorry", "Id", "Model", "Capacity", "Crew", "Crew cap",
         "Round", "Scrap?", "Tenure", "Status"],
        numeric_cols=(1, 3, 4, 5))]
    for i, t in enumerate(fleet.trucks):
        band = "band" if i % 2 else None
        rows.append(_row([
            _cell(f"L{t['id']}", band),
            _cell(t["id"], band),
            _cell(t.get("model_name", "Standard"), band),
            _cell(int(t["capacity"]), band),
            _cell(t["crew"], band),
            _cell(t.get("crew_cap", 3), band),
            _cell(_truck_round_label(game, t), band),
            _cell("No", band),
            _cell("Leased" if t.get("leased") else "Owned", band),
            _cell(t["state"], band),
        ]))
    if not fleet.trucks:
        rows.append(_row([_cell("(no vehicles)", "note")]))
    sheets.append(_sheet("Fleet",
                         [60, 40, 150, 80, 55, 70, 110, 60, 70, 90], rows))

    # -- Catalogue (read-only reference) ------------------------------------
    rows = [_header_row(
        ["Model id", "Model", "Capacity", "Crew cap", "Speed x", "Price (GBP)",
         "Lease/week (GBP)", "Lease deposit (GBP)", "Running/day (GBP)",
         "Lead (days)", "Notes"],
        numeric_cols=(2, 3, 4, 5, 6, 7, 8, 9))]
    for i, v in enumerate(VEHICLE_CATALOGUE):
        band = "band" if i % 2 else None
        rows.append(_row([
            _cell(v.id, band),
            _cell(v.name, band),
            _cell(v.capacity, band),
            _cell(v.crew_cap, band),
            _cell(v.speed_factor, band),
            _cell(v.price, "money"),
            _cell(v.lease_weekly, "money"),
            _cell(v.deposit(), "money"),
            _cell(v.running_cost, "money"),
            _cell(v.lead_time, band),
            _cell(v.blurb, "note"),
        ]))
    sheets.append(_sheet("Catalogue",
                         [70, 160, 80, 70, 60, 100, 110, 120, 110, 70, 300], rows))

    # -- Place Orders (editable: set Quantity > 0 to order) -----------------
    rows = [_header_row(
        ["Model id", "Quantity", "Tenure (Buy/Lease)", "Up-front each (GBP)",
         "Lead (days)", "Note"],
        numeric_cols=(1, 3, 4))]
    for i, v in enumerate(VEHICLE_CATALOGUE):
        band = "band" if i % 2 else None
        rows.append(_row([
            _cell(v.id, band),
            _cell(0, band),
            _cell("Buy", band),
            _cell(v.price, "money"),
            _cell(v.lead_time, band),
            _cell(f"{v.name} -- lease deposit GBP{v.deposit()}", "note"),
        ]))
    sheets.append(_sheet("Place Orders", [80, 80, 130, 130, 80, 320], rows))

    # -- Procurement Orders (read-only -- vehicles already on order) --------
    rows = [_header_row(
        ["Model", "Ordered (day)", "Arrives (day)", "Days left", "Tenure"],
        numeric_cols=(1, 2, 3))]
    for o in fleet.orders:
        rows.append(_row([
            _cell(o.vehicle.name),
            _cell(o.order_day),
            _cell(o.arrival_day),
            _cell(o.days_remaining(eco.day)),
            _cell("Leased" if o.leased else "Owned"),
        ]))
    if not fleet.orders:
        rows.append(_row([_cell("(nothing on order)", "note")]))
    sheets.append(_sheet("Procurement Orders", [160, 100, 100, 90, 80], rows))

    # -- Config (editable difficulty / pacing levers) -----------------------
    rows = [_header_row(["Item", "Value"], numeric_cols=(1,))]
    rows.append(_row([_cell(LV_DAY_LENGTH, "label"),
                      _cell(round(eco.day_duration, 1))]))
    rows.append(_row([_cell(LV_EVENT_CHANCE, "label"),
                      _cell(round(eco.event_chance, 2))]))
    rows.append(_row([_cell(LV_WIN_TARGET, "label"),
                      _cell(eco.win_streak_target)]))
    sheets.append(_sheet("Config", [320, 110], rows))

    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<?mso-application progid="Excel.Sheet"?>\n'
        '<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n'
        ' xmlns:o="urn:schemas-microsoft-com:office:office"\n'
        ' xmlns:x="urn:schemas-microsoft-com:office:excel"\n'
        ' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"\n'
        ' xmlns:html="http://www.w3.org/TR/REC-html40">\n'
        ' <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">\n'
        f'  <Title>Borough Waste Services - Management Plan</Title>\n'
        f'  <Author>{escape(PRODUCT)}</Author>\n'
        f'  <Company>Borough Waste Services</Company>\n'
        f'  <Created>{datetime.datetime.now().isoformat()}</Created>\n'
        ' </DocumentProperties>\n'
        ' <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">\n'
        '  <WindowHeight>9000</WindowHeight><WindowWidth>16000</WindowWidth>\n'
        ' </ExcelWorkbook>\n'
    )
    return head + _STYLES + "".join(sheets) + "\n</Workbook>\n"


# ===========================================================================
#  Reading (XML)
# ===========================================================================
def _localname(tag):
    return tag.split("}", 1)[-1]


def _parse_xml(xml_text):
    """Parse SpreadsheetML into {sheet_name: [ {header: value}, ... ]}."""
    if isinstance(xml_text, bytes):
        xml_text = xml_text.decode("utf-8", "replace")
    root = ET.fromstring(xml_text)
    SS = "{urn:schemas-microsoft-com:office:spreadsheet}"
    sheets = {}
    for ws in root.iter():
        if _localname(ws.tag) != "Worksheet":
            continue
        name = ws.get(SS + "Name") or ws.get("Name") or "Sheet"
        table = None
        for child in ws:
            if _localname(child.tag) == "Table":
                table = child
                break
        if table is None:
            continue
        grid = []
        for row in table:
            if _localname(row.tag) != "Row":
                continue
            cells = []
            col = 0
            for cell in row:
                if _localname(cell.tag) != "Cell":
                    continue
                idx = cell.get(SS + "Index")
                if idx:
                    col = int(idx) - 1
                while len(cells) < col:
                    cells.append("")
                value = ""
                for data in cell:
                    if _localname(data.tag) == "Data":
                        value = data.text or ""
                        break
                cells.append(value)
                col += 1
            grid.append(cells)
        if not grid:
            sheets[name] = []
            continue
        headers = [h.strip() for h in grid[0]]
        rowdicts = []
        for cells in grid[1:]:
            d = {}
            for i, h in enumerate(headers):
                d[h] = cells[i] if i < len(cells) else ""
            rowdicts.append(d)
        sheets[name] = rowdicts
    return sheets


def _to_float(s, default=None):
    try:
        return float(str(s).replace(",", "").replace("GBP", "").strip())
    except (ValueError, AttributeError):
        return default


def apply_workbook(game, sheets):
    """Apply the editable levers from a parsed workbook. Returns a summary
    string and records a detailed report on the game for the next export."""
    eco = game.economy
    city = game.city
    fleet = game.fleet
    waste = game.waste
    notes = []
    warnings = []

    # Rounds (match by stable Id, fall back to name) -------------------------
    rounds = sheets.get("Collection Rounds", [])
    by_name = {a.name.strip().lower(): a for a in city.areas}
    moved = 0
    for r in rounds:
        area = None
        rid = _to_float(r.get("Id"))
        if rid is not None:
            area = city.get_area(int(rid))
        if area is None:
            area = by_name.get((r.get("Round") or "").strip().lower())
        if not area:
            name = (r.get("Round") or "").strip()
            if name:
                warnings.append(f"round '{name}' not found")
            continue
        di = _day_index(r.get("Collection day"))
        if di is not None and di != area.collection_day:
            city.set_area_day(area.id, di)
            moved += 1
        freq = (r.get("Frequency") or "").strip().lower()
        if freq.startswith("fort") and area.frequency != 2:
            area.frequency = 2
            moved += 1
        elif freq.startswith("week") and area.frequency != 1:
            area.frequency = 1
            moved += 1
    if moved:
        notes.append(f"{moved} round change(s)")

    # Waste streams (toggle, frequency, and now economics) -------------------
    streams = sheets.get("Waste Streams", [])
    if streams:
        changed = waste.apply_rows(streams)
        if changed:
            notes.append(f"{changed} waste-stream change(s)")

    # Finance rates ----------------------------------------------------------
    fin = sheets.get("Finance", [])
    rate_changes = 0
    for r in fin:
        if (r.get("Type") or "").strip().lower() != "rate":
            continue
        item = (r.get("Item") or "").strip()
        val = _to_float(r.get("Value"))
        if val is None:
            continue
        if item == LV_COUNCIL_TAX:
            new = max(0.0, round(val, 2))
            if abs(new - eco.council_tax_rate) > 1e-9:
                eco.council_tax_rate = new; rate_changes += 1
        elif item == LV_BUSINESS:
            new = max(0.0, round(val, 2))
            if abs(new - eco.business_rates) > 1e-9:
                eco.business_rates = new; rate_changes += 1
        elif item == LV_WAGE:
            new = max(0.0, round(val, 2))
            if abs(new - eco.hourly_wage_rate) > 1e-9:
                eco.hourly_wage_rate = new; rate_changes += 1
    if rate_changes:
        notes.append(f"{rate_changes} finance rate(s)")

    # Routes -----------------------------------------------------------------
    for r in sheets.get("Routes", []):
        if (r.get("Item") or "").strip() == LV_THRESHOLD:
            val = _to_float(r.get("Value"))
            if val is not None:
                new = int(max(5, min(80, val)))
                if new != fleet.service_threshold:
                    fleet.service_threshold = new
                    notes.append("service threshold")

    # Config (difficulty / pacing levers) ------------------------------------
    for r in sheets.get("Config", []):
        item = (r.get("Item") or "").strip()
        val = _to_float(r.get("Value"))
        if val is None:
            continue
        if item == LV_DAY_LENGTH:
            new = max(5.0, min(600.0, round(val, 1)))
            if abs(new - eco.day_duration) > 1e-6:
                eco.day_duration = new
                notes.append("day length")
        elif item == LV_EVENT_CHANCE:
            new = max(0.0, min(1.0, round(val, 2)))
            if abs(new - eco.event_chance) > 1e-9:
                eco.event_chance = new
                notes.append("event chance")
        elif item == LV_WIN_TARGET:
            new = int(max(1, min(60, val)))
            if new != eco.win_streak_target:
                eco.win_streak_target = new
                notes.append("win target")

    # Staff target (hire within budget / fire down -- never overspends) ------
    for r in sheets.get("Staff", []):
        if (r.get("Item") or "").strip() == LV_TARGET_CREW:
            val = _to_float(r.get("Value"))
            if val is None:
                continue
            target = int(max(0, min(60, val)))
            hired = fired = 0
            while fleet.workers < target and eco.budget >= 2500:
                eco.budget -= 2500
                fleet.hire_worker()
                hired += 1
            while fleet.workers > target:
                if not fleet.fire_worker():
                    break
                fired += 1
            if hired:
                notes.append(f"hired {hired} crew")
            if fired:
                notes.append(f"released {fired} crew")
            if fleet.workers < target:
                warnings.append("staff target not fully met (budget)")

    # Fleet: scrap, crew reallocation, round assignment ----------------------
    try:
        _apply_fleet_sheet(game, sheets.get("Fleet", []), notes, warnings)
    except Exception as exc:                       # never abort the whole import
        warnings.append(f"fleet sheet skipped ({exc})")

    # Place Orders: order vehicles within budget -----------------------------
    try:
        _apply_place_orders(game, sheets.get("Place Orders", []), notes, warnings)
    except Exception as exc:
        warnings.append(f"orders sheet skipped ({exc})")

    # Record a report for the next export's Summary sheet --------------------
    report = list(notes) + [f"Warning: {w}" for w in warnings]
    game.last_import_report = report
    game.last_import_stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    if not notes and not warnings:
        return "Plan imported -- no changes to apply (values already match)."
    msg = "Plan imported"
    if notes:
        msg += ": " + ", ".join(notes)
    if warnings:
        n = len(warnings)
        msg += f" ({n} warning{'s' if n != 1 else ''} -- see Summary)"
    return msg + "."


def _apply_fleet_sheet(game, fleet_rows, notes, warnings):
    """Apply scrap / crew / round edits from the Fleet sheet."""
    fleet = game.fleet
    scrap_ids = []
    crew_dist = {}
    round_assign = []
    for r in fleet_rows:
        tid = _to_float(r.get("Id"))
        if tid is None:
            continue
        tid = int(tid)
        if fleet.get_truck(tid) is None:
            warnings.append(f"lorry id {tid} not found")
            continue
        if (r.get("Scrap?") or "").strip().lower() in ("yes", "y", "true", "1", "scrap"):
            scrap_ids.append(tid)
            continue
        crew = _to_float(r.get("Crew"))
        if crew is not None:
            crew_dist[tid] = int(max(0, crew))
        round_assign.append((tid, r.get("Round")))

    # Scrap first so the crew pool is correct before redistribution.
    scrapped = 0
    for tid in scrap_ids:
        if fleet.scrap_truck(tid):
            scrapped += 1
            crew_dist.pop(tid, None)
    if scrapped:
        notes.append(f"scrapped {scrapped} lorr{'y' if scrapped == 1 else 'ies'}")

    # Round assignments.
    reassigned = 0
    for tid, cell in round_assign:
        t = fleet.get_truck(tid)
        if t is None:
            continue
        aid = _round_id_from_cell(game, cell)
        if t.get("preferred_area", -1) != aid:
            fleet.assign_truck_area(tid, aid)
            reassigned += 1
    if reassigned:
        notes.append(f"{reassigned} round assignment(s)")

    # Crew redistribution against the now-final pool.
    if crew_dist:
        moved_crew = fleet.set_fleet_crew(crew_dist)
        if moved_crew:
            notes.append(f"reallocated crew on {moved_crew} lorry(ies)")


def _apply_place_orders(game, rows, notes, warnings):
    """Place vehicle orders from the Place Orders sheet, within budget."""
    eco = game.economy
    fleet = game.fleet
    for r in rows:
        vid = (r.get("Model id") or "").strip()
        if not vid:
            continue
        qty = _to_float(r.get("Quantity"))
        if qty is None or qty <= 0:
            continue
        qty = int(min(10, qty))
        v = get_vehicle(vid)
        if not v:
            warnings.append(f"unknown vehicle id '{vid}' in Place Orders")
            continue
        leased = _is_lease(r.get("Tenure (Buy/Lease)") or r.get("Tenure"))
        placed = 0
        afford = True
        for _ in range(qty):
            ok, cost, _msg = fleet.order_vehicle(vid, leased)
            if not ok:
                break
            if eco.budget < cost:
                fleet.orders.pop()
                afford = False
                break
            eco.budget -= cost
            placed += 1
        if placed:
            notes.append(f"ordered {placed}x {v.name} "
                         f"({'lease' if leased else 'buy'})")
        if not afford:
            warnings.append(f"could not afford all {qty}x {v.name} "
                            f"(placed {placed})")


# ===========================================================================
#  Unified export/import (auto-detects format)
# ===========================================================================

def default_export_path(format="ods"):
    base = os.path.join(os.path.expanduser("~"), f"BoroughWaste_Plan.{format}")
    return base


def export_to_path(game, path):
    """Export to either ODS or XML based on file extension."""
    ext = os.path.splitext(path)[1].lower()
    if ext == ".ods":
        if not _has_pyexcel_ods():
            raise ImportError("pyexcel-ods is required for ODS export. Install it with: pip install pyexcel-ods")
        return export_to_ods_path(game, path)
    else:
        # Default to XML
        xml = build_workbook_xml(game)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(xml)
        return path


def import_from_path(game, path):
    """Import from either ODS or XML based on file extension."""
    ext = os.path.splitext(path)[1].lower()
    if ext == ".ods":
        if not _has_pyexcel_ods():
            raise ImportError("pyexcel-ods is required for ODS import. Install it with: pip install pyexcel-ods")
        return import_from_ods_path(game, path)
    else:
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        sheets = _parse_xml(text)
        return apply_workbook(game, sheets)


# ===========================================================================
#  File dialogs (with format selection)
# ===========================================================================

def _file_dialog(save, default_name="BoroughWaste_Plan.ods"):
    """Open a native open/save dialog via tkinter. Returns a path or None.
    Returns the sentinel 'NO_TK' if tkinter is unavailable."""
    try:
        import tkinter
        from tkinter import filedialog
    except Exception:
        return "NO_TK"
    try:
        root = tkinter.Tk()
        root.withdraw()
        root.attributes("-topmost", True)

        if save:
            # Default to ODS, but allow XML too
            opts = dict(
                defaultextension=".ods",
                filetypes=[
                    ("ODS Spreadsheet", "*.ods"),
                    ("XML Spreadsheet 2003", "*.xml"),
                    ("All files", "*.*")
                ],
                title="Save borough plan",
                initialfile=default_name,
            )
            path = filedialog.asksaveasfilename(**opts)
        else:
            opts = dict(
                filetypes=[
                    ("ODS Spreadsheet", "*.ods"),
                    ("XML Spreadsheet 2003", "*.xml"),
                    ("All files", "*.*")
                ],
                title="Import borough plan"
            )
            path = filedialog.askopenfilename(**opts)
        root.destroy()
        return path or None
    except Exception:
        return "NO_TK"


def prompt_export(game):
    """Returns (ok, message)."""
    path = _file_dialog(save=True)
    if path == "NO_TK":
        path = default_export_path("ods")
        try:
            export_to_path(game, path)
            return True, f"Saved to {path} (no file dialog available)."
        except Exception as exc:
            return False, f"Export failed: {exc}"
    if not path:
        return False, "Export cancelled."
    try:
        export_to_path(game, path)
        ext = os.path.splitext(path)[1].upper()
        return True, f"Exported plan to {os.path.basename(path)} ({ext} format)."
    except Exception as exc:
        return False, f"Export failed: {exc}"


def prompt_import(game):
    """Returns (ok, message)."""
    path = _file_dialog(save=False)
    if path == "NO_TK":
        # Try ODS first, then XML
        for ext in ["ods", "xml"]:
            path = default_export_path(ext)
            if os.path.exists(path):
                break
        else:
            return False, "No file dialog and no default plan to import."
    if not path:
        return False, "Import cancelled."
    if not os.path.exists(path):
        return False, "File not found."
    try:
        msg = import_from_path(game, path)
        ext = os.path.splitext(path)[1].upper()
        return True, f"{msg} ({ext} format)."
    except ET.ParseError as exc:
        return False, f"Could not parse file: {exc}"
    except Exception as exc:
        return False, f"Import failed: {exc}"
